version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/data:/bitnami/zookeeper/data

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test_topic:1:1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka/data:/bitnami/kafka/data

  producer:
    build: ./producer
    depends_on:
      - kafka


  consumer:
    build: ./consumer
    depends_on:
      - kafka
  spark:
    image: bitnami/spark
    ports:
      - "4040:4040"
    volumes:
      - ./spark/app:/opt/bitnami/spark/work-dir
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

