
# Use the official Apache Spark base image
FROM apache/spark:3.2.0

# Copy your PySpark application code into the container
COPY pyspark_app.py /app/

# Set the working directory inside the container
WORKDIR /app
